// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PickImportFile() {
  return window['go']['main']['App']['PickImportFile']();
}

export function PickImportPreview() {
  return window['go']['main']['App']['PickImportPreview']();
}

export function SaveFileBase64(arg1, arg2) {
  return window['go']['main']['App']['SaveFileBase64'](arg1, arg2);
}

export function SaveResultsXLSX(arg1, arg2) {
  return window['go']['main']['App']['SaveResultsXLSX'](arg1, arg2);
}
