// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function PickImportFile():Promise<main.FilePayload>;

export function PickImportPreview():Promise<main.ImportPreviewPayload>;

export function SaveFileBase64(arg1:string,arg2:string):Promise<string>;

export function SaveResultsXLSX(arg1:string,arg2:Array<main.ExportRow>):Promise<string>;
